[build]
  command = "pnpm run build"
  publish = "dist"

[[redirects]]
  from = "/thank-you"
  to = "/thank-you/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
